"""The committed constellation scenario and its generator must not drift apart.

scripts/multi-node/constellation.resc is generated by tools/gen_constellation.py and committed
anyway, because a scenario a human can open and read is worth having and because `make exercise`
and the e2e tests include it by path. Two copies of one fact, which is the arrangement this
repository has been bitten by three times - identity.cmake beside identity.py, the Makefile's OUT
beside paths.py, the two language maps in CLAUDE.md. Each time the fix was a test comparing them.

Compared by COMMAND, not by text: the generator's prose and the file's prose may differ, and the
thing that must not change is the topology.
"""
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "tools"))
sys.path.insert(0, str(REPO / "src"))

import gen_constellation                                   # noqa: E402
from cuberange.identity import MAX_SATELLITES              # noqa: E402

COMMITTED = REPO / "scripts" / "multi-node" / "constellation.resc"


def commands(text: str) -> list[str]:
    return [ln.strip() for ln in text.splitlines()
            if ln.strip() and not ln.strip().startswith(("#", ":"))]


def test_the_committed_scenario_is_what_the_generator_emits():
    mine = commands(gen_constellation.render(2))
    theirs = commands(COMMITTED.read_text())
    assert theirs == mine, (
        "scripts/multi-node/constellation.resc no longer matches "
        "`python3 tools/gen_constellation.py 2`. Regenerate it, or change the generator - but do "
        "not edit the scenario by hand, because every other satellite count comes from here.")


def test_the_generator_produces_one_hub_per_spacecraft():
    """The failure mode CLAUDE.md records: reuse a hub name and every machine joins one bus,
    nothing reports it, and an attack on one spacecraft lands on the other."""
    for n in range(1, MAX_SATELLITES + 1):
        cmds = commands(gen_constellation.render(n))
        hubs = [c for c in cmds if c.startswith("emulation CreateCANHub")]
        assert len(hubs) == n, f"{n} spacecraft produced {len(hubs)} hubs"
        assert len(set(hubs)) == n, f"duplicate hub name among {hubs}"


def test_every_node_joins_its_own_spacecraft_hub():
    for n in (2, MAX_SATELLITES):
        text = gen_constellation.render(n)
        current = None
        for line in commands(text):
            if line.startswith('mach create "SAT'):
                current = line.split('"')[1].split("_")[0]        # SAT2
            elif line.startswith("connector Connect sysbus.fdcan1"):
                hub = line.split()[-1]                            # canHub2
                assert current is not None
                assert hub == "canHub" + current[3:], (
                    f"{current} is joined to {hub}, which belongs to another spacecraft")


def test_each_spacecraft_gets_four_nodes_and_one_link():
    for n in (1, 2, MAX_SATELLITES):
        cmds = commands(gen_constellation.render(n))
        assert sum(1 for c in cmds if c.startswith("mach create")) == 4 * n
        links = [c for c in cmds if c.startswith("emulation CreateServerSocketTerminal")]
        assert len(links) == n, f"{n} spacecraft produced {len(links)} space links"
        assert len(set(links)) == n, f"two spacecraft share a link port: {links}"


def test_satellite_zero_keeps_the_build_directories_everything_else_names():
    """CLAUDE.md: do not renumber satellite 0. That applies to its images too - the exercises
    and write-ups name build-comm, build-obc, build-eps-vuln and build-adcs-vuln directly."""
    cmds = commands(gen_constellation.render(2))
    for expected in ("build-comm/", "build-obc/", "build-eps-vuln/", "build-adcs-vuln/"):
        assert any(expected in c and "0?=" in c for c in cmds), (
            f"satellite 0 no longer loads from {expected}")


def test_a_count_past_the_addressing_limit_is_refused():
    """CSP v1 addresses are five bits. identity.cmake refuses the same range at build time."""
    with pytest.raises(ValueError):
        gen_constellation.render(MAX_SATELLITES + 1)
    with pytest.raises(ValueError):
        gen_constellation.render(0)


def test_the_tool_runs():
    proc = subprocess.run([sys.executable, str(REPO / "tools" / "gen_constellation.py"), "3"],
                          capture_output=True, text=True, timeout=60)
    assert proc.returncode == 0, proc.stderr
    assert proc.stdout.count("mach create") == 12
