"""CubeSat Space Protocol v1 and its CAN Fragmentation Protocol, encoder side.

The satellite runs libcsp; this is the ground/attacker side, which needs to *forge* frames rather
than participate politely. It is written from libcsp's documented layout and checked against
golden vectors generated by running libcsp itself (tests/golden/csp.json), so a divergence shows
up as a failing test rather than as a packet the satellite silently ignores.

CSP v1 header, 4 octets, big endian (libcsp/src/csp_id.c:29-41):
    bits 31-30  priority
    bits 29-25  source            <- source is at the HIGHER offset; the ASCII art in libcsp's
    bits 24-20  destination          own header lists SOURCE first and the code agrees
    bits 19-14  destination port
    bits 13-8   source port
    bits 7-0    flags

CFP v1 CAN identifier, 29 bits (libcsp/include/csp/interfaces/csp_if_can.h:77-119):
    bits 28-24  source (5)
    bits 23-19  destination (5)
    bit  18     type, 0 = BEGIN, 1 = MORE
    bits 17-10  remaining fragment count (8)
    bits 9-0    CFP transfer identifier (10)

A BEGIN frame carries the 4-octet CSP header, a 2-octet big-endian length, and up to 2 data
octets. Every MORE frame carries up to 8 raw data octets.

CSP v2 is a 48-bit header and is not wire-compatible; P1 is v1 only.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

CSP_HEADER_LEN = 4
CAN_MAX_DLC = 8
BEGIN = 0
MORE = 1

# Node addresses used across CubeRange.
ADDR_OBC = 1
ADDR_EPS = 2
ADDR_ADCS = 4
ADDR_COMM = 5


def encode_header(priority: int, src: int, dst: int, dport: int, sport: int,
                  flags: int = 0) -> bytes:
    """Encode the 4-octet CSP v1 header."""
    for name, value, limit in (("priority", priority, 0x3), ("src", src, 0x1F),
                               ("dst", dst, 0x1F), ("dport", dport, 0x3F),
                               ("sport", sport, 0x3F), ("flags", flags, 0xFF)):
        if not 0 <= value <= limit:
            raise ValueError(f"{name}={value} does not fit (max {limit})")
    word = ((priority & 0x3) << 30 | (src & 0x1F) << 25 | (dst & 0x1F) << 20
            | (dport & 0x3F) << 14 | (sport & 0x3F) << 8 | (flags & 0xFF))
    return word.to_bytes(4, "big")


def decode_header(raw: bytes) -> dict:
    if len(raw) < CSP_HEADER_LEN:
        raise ValueError(f"CSP header needs 4 octets, got {len(raw)}")
    word = int.from_bytes(raw[:4], "big")
    return {
        "priority": (word >> 30) & 0x3,
        "src": (word >> 25) & 0x1F,
        "dst": (word >> 20) & 0x1F,
        "dport": (word >> 14) & 0x3F,
        "sport": (word >> 8) & 0x3F,
        "flags": word & 0xFF,
    }


def cfp_can_id(src: int, dst: int, frame_type: int, remain: int, transfer_id: int) -> int:
    """Build the 29-bit CFP identifier."""
    if not 0 <= remain <= 0xFF:
        raise ValueError(f"remain={remain} does not fit in 8 bits")
    if not 0 <= transfer_id <= 0x3FF:
        raise ValueError(f"transfer_id={transfer_id} does not fit in 10 bits")
    return ((src & 0x1F) << 24 | (dst & 0x1F) << 19 | (frame_type & 1) << 18
            | (remain & 0xFF) << 10 | (transfer_id & 0x3FF))


@dataclass(frozen=True)
class CanFrame:
    can_id: int
    data: bytes

    def hex(self) -> str:
        return f"{self.can_id:08X} {self.data.hex().upper()}"


def encode_packet(src: int, dst: int, dport: int, sport: int, payload: bytes,
                  priority: int = 2, flags: int = 0,
                  transfer_id: int = 0) -> List[CanFrame]:
    """Fragment one CSP packet into CFP-over-CAN frames, exactly as libcsp does.

    `transfer_id` distinguishes concurrent transfers; libcsp auto-increments it. A forger may
    pick any value, which is itself a fact an exercise can use.
    """
    header = encode_header(priority, src, dst, dport, sport, flags)
    length = len(payload)

    # BEGIN carries header(4) + length(2) + up to 2 data octets.
    first_data = payload[:CAN_MAX_DLC - 6]
    remain = (length + 6 - 1) // 8
    frames = [CanFrame(cfp_can_id(src, dst, BEGIN, remain, transfer_id),
                       header + length.to_bytes(2, "big") + first_data)]

    sent = len(first_data)
    while sent < length:
        chunk = payload[sent:sent + CAN_MAX_DLC]
        remain = (length - sent - len(chunk) + CAN_MAX_DLC - 1) // CAN_MAX_DLC
        frames.append(CanFrame(cfp_can_id(src, dst, MORE, remain, transfer_id), chunk))
        sent += len(chunk)

    return frames


def decode_cfp_id(can_id: int) -> Tuple[int, int, int, int, int]:
    """(src, dst, type, remain, transfer_id) from a 29-bit CFP identifier."""
    return ((can_id >> 24) & 0x1F, (can_id >> 19) & 0x1F, (can_id >> 18) & 1,
            (can_id >> 10) & 0xFF, can_id & 0x3FF)
