#!/usr/bin/env python3
"""Generate the constellation scenario from the identity module, rather than restating it.

Two spacecraft was 140 lines of .resc in which the only things that varied were an index and a
hub name. Four would be 280, and the repetition is exactly where a hub name gets reused by
accident - which CLAUDE.md records as a failure mode that produces no error message: two
scenarios that both say `canHub` join every machine to one bus, and the symptom is an attack on
one spacecraft landing on the other.

So this derives the scenario from `cuberange.identity` and `cuberange.ports`, the two modules
that already own who is who and what listens where. A satellite count is a parameter, and
identity.cmake refuses an index past 3 for the same reason this does: CSP v1 addresses are five
bits wide.

    python3 tools/gen_constellation.py 4 > scripts/multi-node/constellation4.resc
    make constellation SATS=4

tests/pytest/test_gen_constellation.py checks that what this emits for two spacecraft is
behaviourally what the committed scenario does - same machines, same hubs, same one-hub-per-
spacecraft property - because a generator that quietly changed the topology would invalidate
every exercise built on it.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from cuberange import ports                                   # noqa: E402
from cuberange.identity import MAX_SATELLITES, spacecraft     # noqa: E402

ROLES = ("comm", "obc", "eps", "adcs")

HEADER = """:name: CubeRange constellation - {n} spacecraft, {m} nodes
:description: {n} spacecraft on {n} separate CAN hubs, in one emulation

# GENERATED by tools/gen_constellation.py. Edit that, not this.
#
# Everything below is derived from cuberange.identity and cuberange.ports, which already own who
# is who and what listens where. The hand-written version repeated the same eleven lines per node
# with an index changed, and the repetition is where a hub name gets reused by accident - two
# scenarios that both say `canHub` join every machine to one bus, nothing reports it, and the
# symptom is an attack on one spacecraft landing on the other.

$profile?=@~/space-cs-sim/scripts/profiles/interactive.resc
include $profile

# $out has NO default. Unset, LoadELF fails where you can see it, which beats loading another
# checkout's firmware in silence. The harness passes it; for a manual run so must you:
#   renode -e '$out=@'"$(make -s out)" -e 'include @<this file>' -e start
"""

NODE = """
mach create "SAT{i}_{ROLE}"
machine LoadPlatformDescription @platforms/boards/nucleo_h753zi.repl
connector Connect sysbus.fdcan1 canHub{i}
sysbus LoadELF ${role}{i}
sysbus.usart3 CreateFileBackend ${role}{i}uart true
{link}logLevel 3 sysbus
logLevel 3 rcc
logLevel 3 fdcan1
"""

LINK = """emulation CreateServerSocketTerminal $link{i} "spacelink{i}" false
connector Connect sysbus.usart2 spacelink{i}
"""

FOOTER = """
# No attacker machine here. The constellation exists to establish that the spacecraft coexist and
# stay apart; the exercises that need an injector create their own on the hub they are attacking.
# Adding one to every hub by default would put a raw CAN entry point on a spacecraft no exercise
# had asked to expose.
#
# ONE Monitor serves them all, because rule L1 permits exactly one control client per emulation.
# Host code selects a spacecraft with `mach set`, which is why src/cuberange/renode/monitor.py
# serialises the session - a `mach set` from one satellite's poller landing inside another's read
# returns the wrong machine's register with no error anywhere.
"""


def render(n: int) -> str:
    if not 1 <= n <= MAX_SATELLITES:
        raise ValueError(
            f"{n} spacecraft: CSP v1 addresses are five bits, so this range holds "
            f"1..{MAX_SATELLITES}")
    out = [HEADER.format(n=n, m=n * len(ROLES))]

    for i in range(n):
        sat = spacecraft(i)
        out.append(f"\n# satellite {i}: "
                   + " ".join(f"{r.upper()} {sat.address(r)}" for r in ROLES)
                   + f"  SCID 0x{sat.scid:03X}  link {ports.link(i)}\n")
        for role in ROLES:
            build = "build-comm" if (role, i) == ("comm", 0) else None
            out.append(f"${role}{i}?=$out/{_build_dir(role, i)}/zephyr/zephyr.elf\n")
        for role in ROLES:
            out.append(f"${role}{i}uart?=$out/sat{i}-{role}.uart\n")
        out.append(f"$link{i}?={ports.link(i)}\n")

    out.append("\n# One hub per spacecraft. The names are what keeps them apart: hub names are\n"
               "# emulation-scope, and reusing one joins every machine to a single bus.\n")
    for i in range(n):
        out.append(f'emulation CreateCANHub "canHub{i}"\n')

    for i in range(n):
        for role in ROLES:
            out.append(NODE.format(i=i, role=role, ROLE=role.upper(),
                                   link=LINK.format(i=i) if role == "comm" else ""))
    out.append(FOOTER)
    return "".join(out)


def _build_dir(role: str, index: int) -> str:
    """Where `make firmware-sat SAT=<index>` puts each image.

    Satellite 0 keeps the names every existing scenario and write-up already uses; CLAUDE.md says
    not to renumber it, and that applies to its build directories too.
    """
    if index == 0:
        return {"comm": "build-comm", "obc": "build-obc",
                "eps": "build-eps-vuln", "adcs": "build-adcs-vuln"}[role]
    return f"build-{role}-sat{index}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("satellites", nargs="?", type=int, default=2)
    ap.add_argument("-o", "--out", type=Path, help="write here instead of stdout")
    args = ap.parse_args()
    text = render(args.satellites)
    if args.out:
        args.out.write_text(text)
        print(f"{args.out}: {args.satellites} spacecraft, {args.satellites * len(ROLES)} nodes",
              file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
